### ISSUE TITLE
Bar chart align the bars to top/left when hiding changes

### ISSUE THREAD

**Issue by NChristina** [Caleydo/taco#49]
Related to the second issue: Some bars are "flying" when deactivating changes. And some are duplicated!? I assume you have to update the bar chart again to align the bars to top/left.

![image](https://cloud.githubusercontent.com/assets/18003747/22937353/9f66e1c8-f2d8-11e6-909b-4ef2d1d21c81.png)

**Comment by thinkh** [comment]
The histogram is fixed with https://github.com/Caleydo/taco/commit/d0843c3b37b82b20576fa7ac9cef83e378c9c824.

The 2D Ratio is fixed with https://github.com/Caleydo/taco/commit/4eb43eaca44626219374d90f46fba4f88c619562.

![taco_animate-2d-ratio](https://cloud.githubusercontent.com/assets/5851088/24316049/69ede858-10eb-11e7-8510-c2a2610672ce.gif)

**Comment by mstreit** [comment]
Nice!
